### ISSUE TITLE
Fix Ctrl-S Predicate

### ISSUE THREAD

**Issue by spatializes** [iceddev/iggins#8]
Ctrl-S conflicts with Ctrl-Shift-S because Ctrl-S does not define shift as false. Needs to be updated with false shift.

Something like this:

```
CTRL_S: function({ ctrlKey, metaKey, keyCode, shiftKey }){
        return ((ctrlKey === true || metaKey === true) && shiftKey === false && keyCode === 83);
}
```

**Comment by phated** [comment]
Assigning to @urbantumbleweed
